// this file was generated by the OCMock Test template

#import "OCMockTestCase.h"
//#import "NSObject.h"

@interface NSObjectTests : OCMockTestCase

@end



@implementation NSObjectTests {
    NSObject *subject;
}

- (void)setUp
{
    [super setUp];
    
    subject = [[NSObject alloc] init];
}

- (void)tearDown
{
    [super tearDown];
}

- (NSString *)file
{
    return [NSString stringWithUTF8String:__FILE__];
}

@end
